return {
--    'shittened/pendulum-nvim',
--    config = function()
--        require('pendulum').setup({
--            log_file = vim.env.HOME .. '/.config/nvim/pendulum.csv',
--            timeout_len = 180,
--            timer_len = 20,
--            gen_reports = true,
--            top_n = 100, --top entries in report
--            hours_n = 10, --no of entries in active hr reports
--            time_format = '24h',
--            time_zone = 'Europe/Bucharest',
--            report_section_excludes = {'branch', 'project'},
--            report_excludes = {
--                branch = {},
--                directory = {},
--                file = {},
--                filetype = {'neo-tree'},
--                project = {}
--            }
--        })
--    end
}
